name: Build and deploy bitburner-src

on:
  workflow_dispatch:
  push:
    branches: [main]
  repository_dispatch:
    types: [bitburner-src-updated]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
